name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  auto_release:
    runs-on: ubuntu-latest
    steps:
    - name: Create New Release
      uses: softprops/action-gh-release@latest
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
#         repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: "latest"
        prerelease: false
        name: "release"
    	
